window.COLLEGE_PANDA_VOCAB = [
  {"id":"cp-001","term":"erratic","definition":"unpredictable, inconsistent, irregular"},
  {"id":"cp-002","term":"secluded","definition":"hard to reach, hidden away"},
  {"id":"cp-003","term":"fluctuate","definition":"to rise and fall irregularly"},
  {"id":"cp-004","term":"exalt","definition":"to praise, to worship"},
  {"id":"cp-005","term":"admonish","definition":"to warn or scold someone"},
  {"id":"cp-006","term":"abrupt","definition":"sudden, unexpected, without warning"},
  {"id":"cp-007","term":"content","definition":"satisfied"},
  {"id":"cp-008","term":"eccentric","definition":"uncommon, strange"},
  {"id":"cp-009","term":"mired","definition":"stuck in mud"},
  {"id":"cp-010","term":"colloquial","definition":"used in casual conversation"},
  {"id":"cp-011","term":"reconcile","definition":"settle one’s differences, make compatible, bring back to peace"},
  {"id":"cp-012","term":"alienate","definition":"to cause someone to feel isolated or lonely"},
  {"id":"cp-013","term":"distinguish","definition":"to tell the difference between"},
  {"id":"cp-014","term":"adequate","definition":"sufficient, enough, acceptable"},
  {"id":"cp-015","term":"contend","definition":"1) to deal with someone or something 2) to claim or state a belief confidently"},
  {"id":"cp-016","term":"skeptical","definition":"having doubts"},
  {"id":"cp-017","term":"enfranchise","definition":"to give the right to vote"},
  {"id":"cp-018","term":"sophisticated","definition":"1) having a lot of worldly experience and knowledge 2) complicated"},
  {"id":"cp-019","term":"radical","definition":"1) thorough, complete, extensive 2) fundamental, essential 3) revolutionary, extreme"},
  {"id":"cp-020","term":"formulate","definition":"to create or think up"},
  {"id":"cp-021","term":"attest","definition":"to confirm or verify"},
  {"id":"cp-022","term":"vexing","definition":"annoying, irritating"},
  {"id":"cp-023","term":"unassuming","definition":"humble, low-key"},
  {"id":"cp-024","term":"coerce","definition":"to pressure or force someone to do something"},
  {"id":"cp-025","term":"adept","definition":"very skilled at something"},
  {"id":"cp-026","term":"eloquent","definition":"fluent or persuasive in speaking or writing"},
  {"id":"cp-027","term":"austere","definition":"plain and without decoration, comforts, or anything extra"},
  {"id":"cp-028","term":"dread","definition":"to fear, be afraid of"},
  {"id":"cp-029","term":"inevitable","definition":"unavoidable"},
  {"id":"cp-030","term":"to stress","definition":"to emphasize"},
  {"id":"cp-031","term":"spawn","definition":"to produce, generate, or create"},
  {"id":"cp-032","term":"renounce","definition":"to give up, deny, or surrender something"},
  {"id":"cp-033","term":"unprecedented","definition":"never done or known before"},
  {"id":"cp-034","term":"broach","definition":"to bring up a difficulty subject for discussion"},
  {"id":"cp-035","term":"proxy","definition":"a person authorized to act on behalf of another; substitute"},
  {"id":"cp-036","term":"detrimental","definition":"harmful, damaging"},
  {"id":"cp-037","term":"secular","definition":"having no religious or spiritual basis"},
  {"id":"cp-038","term":"innovative","definition":"new and different"},
  {"id":"cp-039","term":"tangible","definition":"real and able to be shown or touched"},
  {"id":"cp-040","term":"disseminate","definition":"to spread widely (particularly information)"},
  {"id":"cp-041","term":"delegate (verb)","definition":"to assign a task to another person"},
  {"id":"cp-042","term":"apparent","definition":"clearly visible or understood; obvious"},
  {"id":"cp-043","term":"postulate","definition":"to suggest or propose something"},
  {"id":"cp-044","term":"speculate","definition":"to guess, to form a theory without firm evidence"},
  {"id":"cp-045","term":"bazaar","definition":"a market selling a large variety of goods"},
  {"id":"cp-046","term":"sporadic","definition":"scattered, irregular, unpredictable"},
  {"id":"cp-047","term":"suffrage","definition":"the right to vote"},
  {"id":"cp-048","term":"incredulous","definition":"unwilling or unable to believe something"},
  {"id":"cp-049","term":"idealistic","definition":"unrealistically aiming for perfection"},
  {"id":"cp-050","term":"conflate","definition":"to mix or combine into one (typically ideas)"},
  {"id":"cp-051","term":"paucity","definition":"poverty, scarcity"},
  {"id":"cp-052","term":"ephemeral","definition":"temporary, short-lived"},
  {"id":"cp-053","term":"prompt","definition":"to cause (someone) to take a course of action"},
  {"id":"cp-054","term":"reverence","definition":"deep respect for someone or something"},
  {"id":"cp-055","term":"disparity","definition":"a great difference"},
  {"id":"cp-056","term":"dispassionate","definition":"not influenced by strong emotion, fair-minded"},
  {"id":"cp-057","term":"phenomenon","definition":"a noteworthy occurrence or situation"},
  {"id":"cp-058","term":"boast","definition":"to brag, to show off"},
  {"id":"cp-059","term":"irksome","definition":"irritating, annoying"},
  {"id":"cp-060","term":"allude","definition":"to suggest or call attention to indirectly, to make a reference to something"},
  {"id":"cp-061","term":"omnipotence","definition":"having unlimited or great power"},
  {"id":"cp-062","term":"provoke","definition":"to cause a reaction or emotion (usually anger); to trigger"},
  {"id":"cp-063","term":"indulge","definition":"to allow oneself to enjoy the pleasure of"},
  {"id":"cp-064","term":"entrenched","definition":"firmly established and unlikely to change"},
  {"id":"cp-065","term":"inherent","definition":"built-in, existing in something as a permanent or essential characteristic"},
  {"id":"cp-066","term":"vernacular","definition":"everyday informal language, local dialect"},
  {"id":"cp-067","term":"inquisition","definition":"interrogation, questioning"},
  {"id":"cp-068","term":"anecdote","definition":"a short personal story"},
  {"id":"cp-069","term":"malign","definition":"evil in nature, harmful"},
  {"id":"cp-070","term":"anomaly","definition":"oddity, something that is not normal"},
  {"id":"cp-071","term":"inhibit","definition":"to hold someone or something back, to suppress, to prevent"},
  {"id":"cp-072","term":"mutable","definition":"changeable"},
  {"id":"cp-073","term":"petty","definition":"1) of little importance 2) caring too much about trivial matters"},
  {"id":"cp-074","term":"avid","definition":"passionate about something"},
  {"id":"cp-075","term":"invoke","definition":"to call on or refer to something"},
  {"id":"cp-076","term":"imprudent","definition":"foolish, reckless"},
  {"id":"cp-077","term":"tenacity","definition":"persistence, determination"},
  {"id":"cp-078","term":"venerable","definition":"respected"},
  {"id":"cp-079","term":"authoritarian","definition":"enforcing strict obedience to authority"},
  {"id":"cp-080","term":"quarrel","definition":"an angry argument or disagreement"},
  {"id":"cp-081","term":"yield","definition":"1) to produce or generate (a result) 2) to surrender"},
  {"id":"cp-082","term":"ambivalent","definition":"having mixed feelings"},
  {"id":"cp-083","term":"endeavor","definition":"to try hard to do something"},
  {"id":"cp-084","term":"insurrection","definition":"a violent uprising or rebellion"},
  {"id":"cp-085","term":"contemplate","definition":"to think about for a long time"},
  {"id":"cp-086","term":"compel","definition":"to force someone to do something"},
  {"id":"cp-087","term":"feasible","definition":"possible to do easily or conveniently"},
  {"id":"cp-088","term":"conjecture","definition":"an opinion or conclusion that is unproven, a guess"},
  {"id":"cp-089","term":"arbitrary","definition":"based on random choice or personal impulse, rather than any reason or system"},
  {"id":"cp-090","term":"reinforce","definition":"to make stronger"},
  {"id":"cp-091","term":"to temper","definition":"to serve as a neutralizing or counterbalancing force to something"},
  {"id":"cp-092","term":"decree","definition":"an official order or command"},
  {"id":"cp-093","term":"brevity","definition":"concise use of words in writing or speech"},
  {"id":"cp-094","term":"equivocal","definition":"open to more than one interpretation; unclear"},
  {"id":"cp-095","term":"stronghold","definition":"a place that is strongly defended, a fortress"},
  {"id":"cp-096","term":"conceive","definition":"to form or create a plan or idea"},
  {"id":"cp-097","term":"vanity","definition":"excessive pride in one’s own appearance or achievements"},
  {"id":"cp-098","term":"sluggish","definition":"slow-moving"},
  {"id":"cp-099","term":"intuition","definition":"instinct, the ability to understand something immediately"},
  {"id":"cp-100","term":"inexorable","definition":"impossible to stop or prevent"},
  {"id":"cp-101","term":"engender","definition":"to cause or give rise to (a feeling, situation, or condition)"},
  {"id":"cp-102","term":"temperament","definition":"a person’s nature, character, or frame of mind"},
  {"id":"cp-103","term":"upheaval","definition":"a sudden change or disruption, chaos"},
  {"id":"cp-104","term":"embrace","definition":"to welcome with open arms, to accept or support willingly"},
  {"id":"cp-105","term":"substantiate","definition":"to show to be true"},
  {"id":"cp-106","term":"superficial","definition":"shallow, on the surface"},
  {"id":"cp-107","term":"sovereignty","definition":"supreme power or authority"},
  {"id":"cp-108","term":"lavish","definition":"luxurious"},
  {"id":"cp-109","term":"crux","definition":"the essence, the main point"},
  {"id":"cp-110","term":"indifference","definition":"lack of interest and concern"},
  {"id":"cp-111","term":"tact","definition":"skillfulness and sensitivity in dealing with others or difficult issues"},
  {"id":"cp-112","term":"abundant","definition":"plentiful"},
  {"id":"cp-113","term":"viable","definition":"capable of working successfully, realistic, doable"},
  {"id":"cp-114","term":"scorn","definition":"contempt, the feeling that someone or something is worthless"},
  {"id":"cp-115","term":"transgress","definition":"misbehave, disobey"},
  {"id":"cp-116","term":"analogy","definition":"a comparison between two things"},
  {"id":"cp-117","term":"objection","definition":"a reason for disagreeing"},
  {"id":"cp-118","term":"construe","definition":"to interpret in a particular way"},
  {"id":"cp-119","term":"procure","definition":"obtain, acquire"},
  {"id":"cp-120","term":"evoke","definition":"to bring to mind"},
  {"id":"cp-121","term":"depiction","definition":"portrayal, illustration"},
  {"id":"cp-122","term":"burden","definition":"a difficulty, problem, or responsibility"},
  {"id":"cp-123","term":"recollection","definition":"a memory; the act of remembering"},
  {"id":"cp-124","term":"tumult","definition":"confusion or disorder"},
  {"id":"cp-125","term":"concede","definition":"admit that something is true after first denying it"},
  {"id":"cp-126","term":"demeanor","definition":"manner, attitude, appearance"},
  {"id":"cp-127","term":"emigration","definition":"the act of leaving one’s own country"},
  {"id":"cp-128","term":"irate","definition":"angry, furious"},
  {"id":"cp-129","term":"tentative","definition":"unconfirmed, subject to change"},
  {"id":"cp-130","term":"merely","definition":"only; just"},
  {"id":"cp-131","term":"deceive","definition":"to trick or mislead someone"},
  {"id":"cp-132","term":"trifling","definition":"unimportant, insignificant"},
  {"id":"cp-133","term":"labyrinthine","definition":"complicated or confusing"},
  {"id":"cp-134","term":"decrepit","definition":"1) weak, disabled 2) in a run-down state, decayed"},
  {"id":"cp-135","term":"corroborate","definition":"to confirm, to verify"},
  {"id":"cp-136","term":"obstinacy","definition":"stubbornness, unwilling to change"},
  {"id":"cp-137","term":"confinement","definition":"imprisonment, captivity"},
  {"id":"cp-138","term":"monotony","definition":"boredom, dullness, lack of variety"},
  {"id":"cp-139","term":"degrade","definition":"treat with disrespect"},
  {"id":"cp-140","term":"dilemma","definition":"a situation in which a difficult choice has to be made between 2 or more alternatives"},
  {"id":"cp-141","term":"conventional","definition":"traditional, accepted, mainstream, standard"},
  {"id":"cp-142","term":"proliferate","definition":"increase or grow rapidly"},
  {"id":"cp-143","term":"aesthetic","definition":"concerned with beauty or the appreciation of beauty"},
  {"id":"cp-144","term":"prominent","definition":"important; famous"},
  {"id":"cp-145","term":"unwieldy","definition":"difficult to carry or move"},
  {"id":"cp-146","term":"unilaterally","definition":"used to indicate that something is done by only one person or group, without the agreement of others"},
  {"id":"cp-147","term":"stimulate","definition":"to trigger, spark, or activate; to excite"},
  {"id":"cp-148","term":"abate","definition":"to become less intense or widespread"},
  {"id":"cp-149","term":"diligent","definition":"hard-working"},
  {"id":"cp-150","term":"relegate","definition":"to downgrade, to lower in rank or status"},
  {"id":"cp-151","term":"demur","definition":"to raise doubts or to protest"},
  {"id":"cp-152","term":"novel","definition":"new or unusual in an interesting way"},
  {"id":"cp-153","term":"abstract","definition":"existing in thought or as an idea but not having a physical or concrete existence; conceptual"},
  {"id":"cp-154","term":"vestigial","definition":"undeveloped, nonfunctional"},
  {"id":"cp-155","term":"preoccupied with","definition":"obsessed with something"},
  {"id":"cp-156","term":"optimistic","definition":"hopeful and confident about the future"},
  {"id":"cp-157","term":"remembrance","definition":"the act of remembering something; a memory"},
  {"id":"cp-158","term":"retain","definition":"to keep, to hold on to"},
  {"id":"cp-159","term":"susceptible","definition":"easily influenced or harmed by something; vulnerable"},
  {"id":"cp-160","term":"strenuous","definition":"difficult, exhausting"},
  {"id":"cp-161","term":"enchantment","definition":"magic, charm, fascination"},
  {"id":"cp-162","term":"subservient","definition":"prepared to obey others, submissive, less important"},
  {"id":"cp-163","term":"empirical","definition":"based on experience rather than theory or pure logic"},
  {"id":"cp-164","term":"hostile","definition":"unfriendly, threatening"},
  {"id":"cp-165","term":"promulgate","definition":"to make widely known, to publicize"},
  {"id":"cp-166","term":"enact","definition":"to make law, to put into practice (a belief, idea, or suggestion)"},
  {"id":"cp-167","term":"abject","definition":"miserable, hopeless, awful"},
  {"id":"cp-168","term":"expend","definition":"to use up, to consume"},
  {"id":"cp-169","term":"yielding","definition":"giving in to or complying with the requests of others"},
  {"id":"cp-170","term":"ignominious","definition":"embarrassing, shameful"},
  {"id":"cp-171","term":"naive","definition":"showing a lack of experience, wisdom, or judgment"},
  {"id":"cp-172","term":"acquisition","definition":"something that is bought or obtained, an act of purchase"},
  {"id":"cp-173","term":"affluent","definition":"wealthy"},
  {"id":"cp-174","term":"consolidate","definition":"1) strengthen 2) combine or unite"},
  {"id":"cp-175","term":"pious","definition":"very religious or spiritual"},
  {"id":"cp-176","term":"aggregate","definition":"collection or sum total"},
  {"id":"cp-177","term":"scatterbrained","definition":"disorganized, forgetful"},
  {"id":"cp-178","term":"yearn","definition":"to have an intense feeling of longing for something"},
  {"id":"cp-179","term":"consummate (adj.)","definition":"complete or perfect, having a high degree of skill"},
  {"id":"cp-180","term":"endorse","definition":"to support"},
  {"id":"cp-181","term":"ascertain","definition":"to find (something) out for certain"},
  {"id":"cp-182","term":"onerous","definition":"involving a lot of effort, difficult"},
  {"id":"cp-183","term":"objective (adj.)","definition":"fair-minded, not influenced by personal feelings"},
  {"id":"cp-184","term":"aspire","definition":"to hope to achieve something or be successful"},
  {"id":"cp-185","term":"obsolete","definition":"no longer produced or used; out of date"},
  {"id":"cp-186","term":"inflammatory","definition":"arousing angry or violent feelings"},
  {"id":"cp-187","term":"sentiment","definition":"a view of or attitude towards a situation or event; a general feeling or opinion"},
  {"id":"cp-188","term":"candor","definition":"honesty"},
  {"id":"cp-189","term":"materialistic","definition":"excessively concerned with material possessions or money"},
  {"id":"cp-190","term":"prejudice","definition":"a dislike or unfair opinion (of someone) that is not based on reason or actual experience"},
  {"id":"cp-191","term":"distinct","definition":"clearly separate and different"},
  {"id":"cp-192","term":"deference","definition":"respect"},
  {"id":"cp-193","term":"extensive","definition":"large in amount or scale"},
  {"id":"cp-194","term":"impose","definition":"1) to force the acceptance of something 2) to cause inconvenience to someone"},
  {"id":"cp-195","term":"articulate","definition":"having the ability to speak fluently and persuasively"},
  {"id":"cp-196","term":"pristine","definition":"original and pure; not spoiled or worn from use"},
  {"id":"cp-197","term":"veranda","definition":"a porch or balcony"},
  {"id":"cp-198","term":"atypical","definition":"unusual, uncommon"},
  {"id":"cp-199","term":"subjugate","definition":"to bring under domination or control, to conquer"},
  {"id":"cp-200","term":"ubiquitous","definition":"everywhere, universal"},
  {"id":"cp-201","term":"altercation","definition":"a noisy argument or disagreement"},
  {"id":"cp-202","term":"robust","definition":"strong and healthy, durable"},
  {"id":"cp-203","term":"subvert","definition":"to damage or weaken the authority of an established system"},
  {"id":"cp-204","term":"melodramatic","definition":"exaggerated, sensationalized, or overemotional"},
  {"id":"cp-205","term":"glut","definition":"an excess supply of something"},
  {"id":"cp-206","term":"antipathy","definition":"hatred, dislike"},
  {"id":"cp-207","term":"perilous","definition":"dangerous"},
  {"id":"cp-208","term":"conception","definition":"1) origin or beginning 2) an idea or concept"},
  {"id":"cp-209","term":"repose","definition":"rest, relaxation"},
  {"id":"cp-210","term":"impede","definition":"to create difficulties for someone or something, resulting in delay"},
  {"id":"cp-211","term":"contradiction","definition":"a combination of statements or ideas that are opposed to one another; inconsistency"},
  {"id":"cp-212","term":"judgmental","definition":"having an excessively critical point of view; disapproving"},
  {"id":"cp-213","term":"dismal","definition":"depressing, gloomy"},
  {"id":"cp-214","term":"ambiguous","definition":"open to more than one interpretation; unclear"},
  {"id":"cp-215","term":"wayward","definition":"difficult to control or predict because of unusual behavior"},
  {"id":"cp-216","term":"implication","definition":"1) a conclusion that can be drawn from something 2) a consequence or result"},
  {"id":"cp-217","term":"deploy","definition":"to bring into effective action"},
  {"id":"cp-218","term":"credibility","definition":"believability, authority"},
  {"id":"cp-219","term":"complacent","definition":"overly satisfied or pleased with oneself"},
  {"id":"cp-220","term":"convoke","definition":"to summon, to call together"},
  {"id":"cp-221","term":"mocking","definition":"making fun of someone or something in a cruel way"},
  {"id":"cp-222","term":"prospect","definition":"the possibility or likelihood of some future event occurring"},
  {"id":"cp-223","term":"amicable","definition":"friendly"},
  {"id":"cp-224","term":"predecessor","definition":"someone or something that came before"},
  {"id":"cp-225","term":"deter","definition":"to discourage (someone) from doing something"},
  {"id":"cp-226","term":"indignation","definition":"anger or annoyance"},
  {"id":"cp-227","term":"fetter","definition":"to restrict or restrain, to put in chains"},
  {"id":"cp-228","term":"rigid","definition":"stiff, firm, unchangeable"},
  {"id":"cp-229","term":"cultivate","definition":"to grow, to develop"},
  {"id":"cp-230","term":"juvenile","definition":"young, childish, immature"},
  {"id":"cp-231","term":"convulsion","definition":"a sudden, violent, irregular movement of the body"},
  {"id":"cp-232","term":"devise","definition":"to plan or invent by careful thought"},
  {"id":"cp-233","term":"immure","definition":"to imprison someone against their will"},
  {"id":"cp-234","term":"perturb","definition":"to make someone anxious or unsettled; to disturb"},
  {"id":"cp-235","term":"solicitude","definition":"care or concern for someone or something"},
  {"id":"cp-236","term":"pervasive","definition":"spreading widely throughout an area or group of people"},
  {"id":"cp-237","term":"tyranny","definition":"cruel and abusive government or rule"},
  {"id":"cp-238","term":"apprehensive","definition":"anxious or fearful that something bad or unpleasant will happen"},
  {"id":"cp-239","term":"provision","definition":"1) a condition or requirement in a legal document 2) the act of providing services or resources"},
  {"id":"cp-240","term":"insolent","definition":"showing a rude lack of respect"},
  {"id":"cp-241","term":"consensus","definition":"general agreement"},
  {"id":"cp-242","term":"discord","definition":"disagreement between people"},
  {"id":"cp-243","term":"complement (verb)","definition":"to add to (something) in a way that enhances or completes it"},
  {"id":"cp-244","term":"mortify","definition":"to cause (someone) to feel embarrassed, ashamed, or humiliated"},
  {"id":"cp-245","term":"dissipate","definition":"to disappear or evaporate"},
  {"id":"cp-246","term":"doctrine","definition":"a belief or set of beliefs"},
  {"id":"cp-247","term":"incomprehensible","definition":"not able to be understood"},
  {"id":"cp-248","term":"recount","definition":"to tell someone about something, to give a report of an event"},
  {"id":"cp-249","term":"inefficacious","definition":"unable to produce the intended result"},
  {"id":"cp-250","term":"adversary","definition":"one’s opponent or enemy"},
  {"id":"cp-251","term":"endow","definition":"to provide, to supply"},
  {"id":"cp-252","term":"confound","definition":"to cause surprise or confusion in someone"},
  {"id":"cp-253","term":"assert","definition":"to state a fact or belief confidently and forcefully"},
  {"id":"cp-254","term":"undermine","definition":"to gradually damage or weaken someone or something"},
  {"id":"cp-255","term":"paradox","definition":"a statement or situation that may be true but seems impossible or difficult to understand because it contains two opposite facts or characteristics"},
  {"id":"cp-256","term":"apt","definition":"appropriate or suitable in the circumstances"},
  {"id":"cp-257","term":"competent","definition":"having the necessary ability, knowledge, or skill to do something successfully"},
  {"id":"cp-258","term":"severity","definition":"the quality of being very unpleasant, unkind, or difficult"},
  {"id":"cp-259","term":"dismay","definition":"a feeling of shock and unhappiness"},
  {"id":"cp-260","term":"usurp","definition":"to take power or control of something by force or without the right to do so"},
  {"id":"cp-261","term":"nostalgic","definition":"feeling happy and also slightly sad when you think about things that happened in the past"},
  {"id":"cp-262","term":"ornate","definition":"having a lot of complex patterns or decoration"},
  {"id":"cp-263","term":"hierarchy","definition":"a system in which people or things are put at various levels or ranks according to their importance"},
  {"id":"cp-264","term":"irrational","definition":"not logical or reasonable"},
  {"id":"cp-265","term":"bluster","definition":"talk intended to seem important or threatening but which is not taken seriously and has little effect"},
  {"id":"cp-266","term":"subordinate","definition":"having a lower or less important position"},
  {"id":"cp-267","term":"malicious","definition":"intending to cause harm; evil"},
  {"id":"cp-268","term":"amend","definition":"to revise, to make changes"},
  {"id":"cp-269","term":"conform","definition":"to behave according to an expectation or rule"},
  {"id":"cp-270","term":"tout","definition":"to advertise or praise something (often to sell it)"},
  {"id":"cp-271","term":"permeate","definition":"to spread throughout something"},
  {"id":"cp-272","term":"incantation","definition":"a series of words said as a magic spell or charm"},
  {"id":"cp-273","term":"impervious","definition":"not able to be influenced, hurt, or damaged"},
  {"id":"cp-274","term":"actuate","definition":"1) to cause (a machine or device) to operate 2) to cause (someone) to act in a particular way"},
  {"id":"cp-275","term":"versatility","definition":"ability to adapt to many different functions or activities"},
  {"id":"cp-276","term":"proclaim","definition":"to announce officially or publicly"},
  {"id":"cp-277","term":"obeisance","definition":"deep respect"},
  {"id":"cp-278","term":"modest","definition":"1) humble, not showy 2) not large in size or amount"},
  {"id":"cp-279","term":"adorn","definition":"to decorate"},
  {"id":"cp-280","term":"solitude","definition":"the state or situation of being alone"},
  {"id":"cp-281","term":"deplete","definition":"to use up the supply or resources of"},
  {"id":"cp-282","term":"solemn","definition":"having or showing serious purpose and determination; formal"},
  {"id":"cp-283","term":"proponent","definition":"a person who supports an idea, plan, or cause"},
  {"id":"cp-284","term":"keen","definition":"sharp; highly developed (usually the senses)"},
  {"id":"cp-285","term":"engulf","definition":"to surround and cover completely"},
  {"id":"cp-286","term":"diverge","definition":"to go in different directions from the same point, to become different"},
  {"id":"cp-287","term":"squalid","definition":"extremely dirty, poor, and unpleasant"},
  {"id":"cp-288","term":"hypothetical","definition":"imagined or suggested but not necessarily real or true"},
  {"id":"cp-289","term":"pressing","definition":"urgent or needing to be dealt with immediately"},
  {"id":"cp-290","term":"solicitation","definition":"a request for money, information, or help"},
  {"id":"cp-291","term":"meddle","definition":"interfere in something that is not one’s concern"},
  {"id":"cp-292","term":"coarse","definition":"1) rough, not smooth 2) rude or offensive in manner or speech"},
  {"id":"cp-293","term":"reproach","definition":"to criticize or express disapproval with someone"},
  {"id":"cp-294","term":"immerse","definition":"1) to put something completely under a liquid 2) to involve someone completely in an activity"},
  {"id":"cp-295","term":"clout","definition":"power and influence (especially in politics or business)"},
  {"id":"cp-296","term":"exacerbate","definition":"to make something that is already bad worse"},
  {"id":"cp-297","term":"dubious","definition":"doubtful"},
  {"id":"cp-298","term":"plausible","definition":"possibly true, able to be believed, reasonable"},
  {"id":"cp-299","term":"notion","definition":"a belief or idea"},
  {"id":"cp-300","term":"impartial","definition":"able to judge something fairly"},
  {"id":"cp-301","term":"swath","definition":"a long strip or area of something"},
  {"id":"cp-302","term":"dabble","definition":"to try an activity in a casual way"},
  {"id":"cp-303","term":"earnest","definition":"sincere and serious"},
  {"id":"cp-304","term":"vitality","definition":"life, energy, and strength"},
  {"id":"cp-305","term":"mimic","definition":"to imitate or copy (someone’s actions or words)"},
  {"id":"cp-306","term":"agitate","definition":"1) to make someone troubled or nervous 2) to campaign for something in public"},
  {"id":"cp-307","term":"practical","definition":"likely to succeed or be effective in real circumstances, relating to actual experience rather than knowledge only"},
  {"id":"cp-308","term":"ominous","definition":"suggesting something unpleasant will happen"},
  {"id":"cp-309","term":"dominion","definition":"1) control over a country or people 2) the land that belongs to a ruler"},
  {"id":"cp-310","term":"pretense","definition":"a false display, an attempt to deceive"},
  {"id":"cp-311","term":"egocentric","definition":"thinking only of oneself; self-centered"},
  {"id":"cp-312","term":"exploit","definition":"to make full use of (a resource), to use (a person) in an unfair or selfish way"},
  {"id":"cp-313","term":"comprise","definition":"to consist of or to be made up of"},
  {"id":"cp-314","term":"plight","definition":"a dangerous, difficult, or otherwise unfortunate situation"},
  {"id":"cp-315","term":"exemplify","definition":"to be a typical example of something"},
  {"id":"cp-316","term":"momentous","definition":"very important (in reference to a decision or event)"},
  {"id":"cp-317","term":"reverberate","definition":"to continue to be heard; to echo repeatedly"},
  {"id":"cp-318","term":"paternal","definition":"behaving or feeling as a father does toward his child"},
  {"id":"cp-319","term":"lament","definition":"to express sadness and regret about something"},
  {"id":"cp-320","term":"mediation","definition":"the process by which someone tries to end a disagreement by helping the two sides to talk about and agree on a solution"},
  {"id":"cp-321","term":"miser","definition":"someone who has a great desire to possess money and hates to spend it"},
  {"id":"cp-322","term":"supple","definition":"bending or able to be bent easily; not stiff; flexible"},
  {"id":"cp-323","term":"oblivious","definition":"not aware of what is happening around you"},
  {"id":"cp-324","term":"sullen","definition":"silent and unpleasant; depressed; gloomy"},
  {"id":"cp-325","term":"imperative","definition":"1) extremely important or urgent 2) something that needs to be done immediately"},
  {"id":"cp-326","term":"reminisce","definition":"to talk about the past with pleasure"},
  {"id":"cp-327","term":"tranquil","definition":"calm, quiet, and peaceful"},
  {"id":"cp-328","term":"cleave","definition":"to cut or split into at least two parts"},
  {"id":"cp-329","term":"reluctance","definition":"an unwillingness to do something"},
  {"id":"cp-330","term":"misgiving","definition":"a feeling of doubt, uncertainty, or worry about a future event"},
  {"id":"cp-331","term":"sparse","definition":"small in number, often spread over a large area; scarce"},
  {"id":"cp-332","term":"progenitor","definition":"originator, creator, founder"},
  {"id":"cp-333","term":"absurd","definition":"ridiculous or completely unreasonable"},
  {"id":"cp-334","term":"premise","definition":"an idea or theory on which a statement or action is based; an assumption"},
  {"id":"cp-335","term":"scrutinize","definition":"to examine someone or something very carefully"},
  {"id":"cp-336","term":"supplemental","definition":"added to something else in order to improve it or complete it"},
  {"id":"cp-337","term":"poignant","definition":"causing a feeling of sadness"},
  {"id":"cp-338","term":"obscure","definition":"not known to many people, difficult to understand"},
  {"id":"cp-339","term":"ancestral","definition":"belonging to or inherited from one’s ancestors"},
  {"id":"cp-340","term":"gregarious","definition":"fond of company; sociable"},
  {"id":"cp-341","term":"exert","definition":"to use power or the ability to make something happen"},
  {"id":"cp-342","term":"vigorous","definition":"strong, healthy, and full of energy"},
  {"id":"cp-343","term":"entreat","definition":"to ask someone sincerely or anxiously to do something"},
  {"id":"cp-344","term":"desolation","definition":"a state of complete emptiness or destruction"},
  {"id":"cp-345","term":"notorious","definition":"famous for something bad"},
  {"id":"cp-346","term":"induce","definition":"1) to persuade someone to do something 2) to cause something to happen"},
  {"id":"cp-347","term":"pompous","definition":"feeling that one is better or more important than other people"},
  {"id":"cp-348","term":"disparage","definition":"to criticize someone or something in a way that shows a lack of respect"},
  {"id":"cp-349","term":"intact","definition":"complete and in the original state; not damaged"},
  {"id":"cp-350","term":"verdict","definition":"an opinion or judgment"},
  {"id":"cp-351","term":"mundane","definition":"ordinary and dull"},
  {"id":"cp-352","term":"spur","definition":"to encourage an activity or development, to cause something to develop faster"},
  {"id":"cp-353","term":"sentinel","definition":"a guard whose job is to stand and keep watch"},
  {"id":"cp-354","term":"convey","definition":"to make (an idea or feeling) known or understandable to someone; to communicate"},
  {"id":"cp-355","term":"render","definition":"to cause someone or something to be in a particular state"},
  {"id":"cp-356","term":"manifest","definition":"to show something clearly, through signs or actions"},
  {"id":"cp-357","term":"continuum","definition":"a continuous sequence; a range"},
  {"id":"cp-358","term":"redress","definition":"to correct a wrong"},
  {"id":"cp-359","term":"underscore","definition":"to emphasize the importance something"},
  {"id":"cp-360","term":"enfeeble","definition":"to make someone or something very weak"},
  {"id":"cp-361","term":"disdain","definition":"dislike of someone or something that one feels does not deserve respect"},
  {"id":"cp-362","term":"flatter","definition":"to praise someone in order to please him or her"},
  {"id":"cp-363","term":"posterity","definition":"all future generations of people"},
  {"id":"cp-364","term":"sustain","definition":"to strengthen or support; to keep alive"},
  {"id":"cp-365","term":"sheer","definition":"1) not mixed with anything else; pure or complete 2) very large"},
  {"id":"cp-366","term":"assess","definition":"to judge the quality or importance of something"},
  {"id":"cp-367","term":"artisan","definition":"a person who does skilled work with his or her hands"},
  {"id":"cp-368","term":"subtle","definition":"not loud, bright, noticeable, or obvious"},
  {"id":"cp-369","term":"repudiate","definition":"to refuse to accept something or someone; to reject"},
  {"id":"cp-370","term":"meander","definition":"to follow a route that is not straight or direct"},
  {"id":"cp-371","term":"effectual","definition":"successful in producing the intended results"},
  {"id":"cp-372","term":"meager","definition":"very small in amount or number"},
  {"id":"cp-373","term":"tedious","definition":"boring, slow, and tiring"},
  {"id":"cp-374","term":"calibrate","definition":"to carefully measure or adjust"},
  {"id":"cp-375","term":"potent","definition":"powerful, persuasive, or effective"},
  {"id":"cp-376","term":"conducive","definition":"providing the right conditions for something to happen or exist; to help bring about"},
  {"id":"cp-377","term":"reserved","definition":"tending to keep feelings or thoughts private; quiet"},
  {"id":"cp-378","term":"medley","definition":"a mixture of different things"},
  {"id":"cp-379","term":"advocate","definition":"1) to support an idea 2) a person who publicly supports an idea"},
  {"id":"cp-380","term":"undulate","definition":"to move with a smooth wavelike motion"},
  {"id":"cp-381","term":"magnitude","definition":"1) the great size or importance of something 2) the extent or degree of something"},
  {"id":"cp-382","term":"aggrandize","definition":"to make someone more powerful or important"},
  {"id":"cp-383","term":"pummel","definition":"to hit someone or something repeatedly"},
  {"id":"cp-384","term":"timid","definition":"easily frightened; shy"},
  {"id":"cp-385","term":"bias","definition":"an unfair personal opinion that influences your judgment"},
  {"id":"cp-386","term":"refine","definition":"to improve something by making small changes"},
  {"id":"cp-387","term":"oscillate","definition":"to swing back and forth"},
  {"id":"cp-388","term":"esteem","definition":"respect and admiration for someone"},
  {"id":"cp-389","term":"displace","definition":"to force something or someone out of its usual or original place"},
  {"id":"cp-390","term":"pulpit","definition":"a raised platform in a church from which the preacher speaks"},
  {"id":"cp-391","term":"ingenious","definition":"clever, original, and inventive (in reference to a person)"},
  {"id":"cp-392","term":"constitute","definition":"to be the parts that form something"},
  {"id":"cp-393","term":"insatiable","definition":"impossible to satisfy"},
  {"id":"cp-394","term":"volition","definition":"the power to make one’s own decisions"},
  {"id":"cp-395","term":"relish","definition":"to like or enjoy something"},
  {"id":"cp-396","term":"facilitate","definition":"to make (an action or process) possible or easier"},
  {"id":"cp-397","term":"threshold","definition":"the level or point at which something starts"},
  {"id":"cp-398","term":"reform","definition":"to make changes in something in order to improve it"},
  {"id":"cp-399","term":"sneer","definition":"to make a facial expression that shows disapproval or disrespect"},
  {"id":"cp-400","term":"profound","definition":"1) intense, extreme 2) requiring deep thought"}
];
